name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository to the GitHub Actions runner
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0
      with:
        # Disable docker pulling of the repository
        context: .
        # Always attempt to pull a newer version of the image
        pull: true
        # Push the build result to a registry
        push: true
        # List of tags
        tags: ghcr.io/guillaume-ro-fr/s3_website:latest
        # Cache with GitHub Actions
        cache-from: type=gha
        cache-to: type=gha,mode=max
